# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Specify your package manager (e.g., npm, pip, maven, gradle, etc.)
    directory: "/"           # Location of the dependency files (e.g., package.json)
    schedule:
      interval: "daily"     # How often to check (daily, weekly, or monthly)
    ignore:
      - dependency-name: "lodash"  # Optional: Exclude specific dependencies
        versions: ["4.17.21"]      # Optional: Ignore specific versions
    commit-message:
      prefix: "deps"   